version: 1.0.{build}

image:
- Visual Studio 2015
- Visual Studio 2017

test: off

build:
  parallel: true

platform:
- x64
- x86

environment:
  matrix:
  - PYTHON: 36
    CPP: 14
    CONFIG: Release
  - PYTHON: 27
    CPP: 14
    CONFIG: Release

#matrix:
#  exclude:
#    - image: Visual Studio 2015
#      platform: x86

install:
- ps: |
    if ($env:PLATFORM -eq "x64") { $env:CMAKE_ARCH = "x64" }
    if ($env:APPVEYOR_JOB_NAME -like "*Visual Studio 2017*") {
      $env:CMAKE_GENERATOR = "Visual Studio 15 2017"
      $env:CXXFLAGS = "-permissive-"
    } else {
      $env:CMAKE_GENERATOR = "Visual Studio 14 2015"
    }
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      pip install --disable-pip-version-check --user --upgrade pip wheel
    } elseif ($env:CONDA) {
      if ($env:CONDA -eq "27") { $env:CONDA = "" }
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
      $env:PYTHONHOME = "C:\Miniconda$env:CONDA"
      conda install -y -q pip
    }
    pip install -U setuptools disttools mpi4py unittest2

build_script:
- ls
- python ./setup.py build install
- python -c "import timemory ; timemory.tests.run()"
