version: 1.0.{build}

image:
- Visual Studio 2015
- Visual Studio 2017

test: off

build:
  parallel: true

platform:
- x64
- x86

environment:
  matrix:
  - PYTHON: 36
    CPP: 14
    CONFIG: Release
  - PYTHON: 27
    CPP: 14
    CONFIG: Release
  - CONDA: 36
    CPP: 17
    CONFIG: Release

matrix:
  exclude:
  - image: Visual Studio 2015
    CPP: latest
  - image: Visual Studio 2017
    CPP: latest
    platform: x86
#  - image: Visual Studio 2015
#    platform: x86

install:
- ps: |
    if ($env:PLATFORM -eq "x64") { $env:CMAKE_ARCH = "x64" }
    if ($env:APPVEYOR_JOB_NAME -like "*Visual Studio 2017*") {
      $env:CMAKE_GENERATOR = "Visual Studio 15 2017"
      $env:CXXFLAGS = "-permissive-"
    } else {
      $env:CMAKE_GENERATOR = "Visual Studio 14 2015"
    }
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      pip install --disable-pip-version-check --user --upgrade pip wheel
    } elseif ($env:CONDA) {
      if ($env:CONDA -eq "27") { $env:CONDA = "" }
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
      $env:PYTHONHOME = "C:\Miniconda$env:CONDA"
      conda update -n base conda
      conda install -y -q pip
    }
    pip install -U setuptools disttools

build_script:
#- mkdir build-timemory
#- cd build-timemory
#- cmake -DCMAKE_SUPPRESS_REGENERATION=1 -DCTEST_LOCAL_CHECKOUT=ON -DCTEST_SITE=AppVeyor
#    -DCTEST_MODEL=Continuous .. -G "%CMAKE_GENERATOR%" -A "%CMAKE_ARCH%"
#- set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#- cmake --build . --config %CONFIG% --target ALL_BUILD -- /m /v:m /logger:%MSBuildLogger%
#- cmake --build . --config %CONFIG% --target INSTALL -- /m /v:m /logger:%MSBuildLogger%
#- ctest -S cdash/Stages.cmake -DSTAGES="Build;Test" -DTRIGGER=Test -V --output-on-failure
#- cd ..
- ls
- pip install .
- cd ..
- python -c "import timemory ; timemory.tests.run()"

