# TiMEemory Travis CI file

language: python


cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"


# The apt packages here install our compiled code dependencies.
matrix:
  include:
    # ------------------------------------------------------------------------ #
    #
    #   Python 2.7
    #
    # ------------------------------------------------------------------------ #
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      python: '2.7'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && SHARED_LINK=OFF"
    # GCC 5
    - os: linux
      dist: trusty
      sudo: false
      python: '2.7'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - build-essential
            - cmake
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which gcc-5) && CXX=$(which g++-5) && SHARED_LINK=ON"
    # GCC 6
    - os: linux
      dist: trusty
      sudo: false
      python: '2.7'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - build-essential
            - cmake
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which gcc-6) && CXX=$(which g++-6) && SHARED_LINK=OFF"
    # GCC 7
    - os: linux
      dist: trusty
      sudo: false
      python: '2.7'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - build-essential
            - cmake
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which gcc-7) && CXX=$(which g++-7) && SHARED_LINK=ON"
    # Clang 4.0
    - os: linux
      dist: trusty
      sudo: false
      python: '2.7'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            - clang++-4.0
            - build-essential
            - cmake
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which clang-4.0) && CXX=$(which clang++-4.0) && SHARED_LINK=OFF"
    # Clang 5.0
    - os: linux
      dist: trusty
      sudo: false
      python: '2.7'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - clang++-5.0
            - build-essential
            - cmake
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which clang-5.0) && CXX=$(which clang++-5.0) && SHARED_LINK=ON"
    # ------------------------------------------------------------------------ #
    #
    #   Python 3.4
    #
    # ------------------------------------------------------------------------ #
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      python: '3.4'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake3
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && SHARED_LINK=OFF"
    # GCC 5
    - os: linux
      dist: trusty
      sudo: false
      python: '3.4'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - build-essential
            - cmake3
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which gcc-5) && CXX=$(which g++-5) && SHARED_LINK=ON"
    # GCC 6
    - os: linux
      dist: trusty
      sudo: false
      python: '3.4'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - build-essential
            - cmake3
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which gcc-6) && CXX=$(which g++-6) && SHARED_LINK=OFF"
    # GCC 7
    - os: linux
      dist: trusty
      sudo: false
      python: '3.4'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - build-essential
            - cmake3
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which gcc-7) && CXX=$(which g++-7) && SHARED_LINK=ON"
    # Clang 4.0
    - os: linux
      dist: trusty
      sudo: false
      python: '3.4'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            - clang++-4.0
            - build-essential
            - cmake3
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which clang-4.0) && CXX=$(which clang++-4.0) && SHARED_LINK=OFF"
    # Clang 5.0
    - os: linux
      dist: trusty
      sudo: false
      python: '3.4'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - clang++-5.0
            - build-essential
            - cmake3
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which clang-5.0) && CXX=$(which clang++-5.0) && SHARED_LINK=ON"
    # ------------------------------------------------------------------------ #
    #
    #   Python 3.5
    #
    # ------------------------------------------------------------------------ #
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      python: '3.5'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake3
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && SHARED_LINK=ON"
    # GCC 5
    - os: linux
      dist: trusty
      sudo: false
      python: '3.5'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - build-essential
            - cmake3
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which gcc-5) && CXX=$(which g++-5) && SHARED_LINK=OFF"
    # GCC 6
    - os: linux
      dist: trusty
      sudo: false
      python: '3.5'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - build-essential
            - cmake3
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which gcc-6) && CXX=$(which g++-6) && SHARED_LINK=ON"
    # GCC 7
    - os: linux
      dist: trusty
      sudo: false
      python: '3.5'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - build-essential
            - cmake3
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which gcc-7) && CXX=$(which g++-7) && SHARED_LINK=OFF"
    # Clang 4.0
    - os: linux
      dist: trusty
      sudo: false
      python: '3.5'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            - clang++-4.0
            - build-essential
            - cmake3
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which clang-4.0) && CXX=$(which clang++-4.0) && SHARED_LINK=ON"
    # Clang 5.0
    - os: linux
      dist: trusty
      sudo: false
      python: '3.5'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - clang++-5.0
            - build-essential
            - cmake3
            - libopenmpi-dev
            - openmpi-bin
      env:
        - MATRIX_EVAL="CC=$(which clang-5.0) && CXX=$(which clang++-5.0) && SHARED_LINK=OFF"
    # ------------------------------------------------------------------------ #
    #
    #   Python 3.6
    #
    # ------------------------------------------------------------------------ #
    # GCC 4.9
    - os: linux
      dist: trusty
      sudo: false
      python: '3.6'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - build-essential
            - cmake
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which gcc-4.9) && CXX=$(which g++-4.9) && SHARED_LINK=ON"
    # GCC 5
    - os: linux
      dist: trusty
      sudo: false
      python: '3.6'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - build-essential
            - cmake
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which gcc-5) && CXX=$(which g++-5) && SHARED_LINK=OFF"
    # GCC 6
    - os: linux
      dist: trusty
      sudo: false
      python: '3.6'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - build-essential
            - cmake
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which gcc-6) && CXX=$(which g++-6) && SHARED_LINK=ON"
    # GCC 7
    - os: linux
      dist: trusty
      sudo: false
      python: '3.6'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - build-essential
            - cmake
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which gcc-7) && CXX=$(which g++-7) && SHARED_LINK=OFF"
    # Clang 4.0
    - os: linux
      dist: trusty
      sudo: false
      python: '3.6'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            - clang++-4.0
            - build-essential
            - cmake
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which clang-4.0) && CXX=$(which clang++-4.0) && SHARED_LINK=ON"
    # Clang 5.0
    - os: linux
      dist: trusty
      sudo: false
      python: '3.6'
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang-5.0
            - clang++-5.0
            - build-essential
            - cmake
            - libmpich-dev
            - mpich
      env:
        - MATRIX_EVAL="CC=$(which clang-5.0) && CXX=$(which clang++-5.0) && SHARED_LINK=OFF"
    # ------------------------------------------------------------------------ #


before_install:
    - eval "${MATRIX_EVAL}"
    - export CC=${CC}
    - export CXX=${CXX}
    - export PYBINPATH=$(dirname $(which python))
    - export PYROOTPATH=$(dirname ${PYBINPATH})
    - export PATH=${PYBINPATH}:${PATH}
    - export CMAKE_PREFIX_PATH=${PYROOTPATH}:${CMAKE_PREFIX_PATH}
    - export PYTHON_VERSION="$(python --version | awk '{print $NF}')"
    - echo "CC = ${CC} $(${CC} -dumpversion)"
    - echo "CXX = ${CXX} $(${CXX} -dumpversion)"
    - echo "Python = $(which python) [version ${PYTHON_VERSION}]"
    - echo "PYBINPATH = ${PYBINPATH}"
    - echo "PYROOTPATH = ${PYROOTPATH}"
    - echo "CMAKE_PREFIX_PATH = ${CMAKE_PREFIX_PATH}"
    - export INSTALL_DIR=${HOME}/timemory/current


install:
    - env
    - echo "--> ${PWD}"
    - export SOURCE_DIR=${PWD}
    - pip install matplotlib numpy pillow
    - mkdir -p build-timemory
    - cd build-timemory
    - export BUILD_DIR=${PWD}
    - echo "CC = ${CC} $(${CC} -dumpversion)"
    - echo "CXX = ${CXX} $(${CXX} -dumpversion)"
    - echo "--> ${PWD}"
    - cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} -DUSE_MPI=ON
        -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=$(which python)
        -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}
        -DBUILD_TESTING=ON -DCTEST_SITE=travis -DCTEST_MODEL=Continous
        -DCTEST_LOCAL_CHECKOUT=ON -DSHARED_PYTHON_LINKING=${SHARED_LINK}
        ${PWD}/..
    - grep '^[A-Za-z]' CMakeCache.txt | grep -vi advanced
    - ctest -S cdash/Stages.cmake -DSTAGES="Build;Test" -DTRIGGER=Test -V --output-on-failure
    #
    # Python testing
    #
    - cd ${SOURCE_DIR}
    - pip install .
    - pip uninstall -y .


script:
    #
    # Python testing
    #
    - mkdir -p ${HOME}/timemory-test
    # go to empty directory for testing
    - cd ${HOME}/timemory-test
    - python${TRAVIS_PYTHON_VERSION} -c "import timemory ; timemory.tests.run()"
    - echo "python${TRAVIS_PYTHON_VERSION} testing -- Done"
