package:
  name: timemory
  version: '2.3.0'

build:
  number: 0

source:
  git_rev: c8bd938bb5923db3c00070c508bf0d553b91d586
  git_url: https://github.com/jrmadsen/TiMemory.git

requirements:
  host:
  - python
  - setuptools
  - cmake

  run:
  - python
  - pillow
  - matplotlib
  - numpy

test:
  imports:
  - timemory
  - timemory.format
  - timemory.mpi_support
  - timemory.options
  - timemory.plotting
  - timemory.signals
  - timemory.units
  - timemory.util

about:
  home: https://jrmadsen.github.io/TiMemory/
  license: MIT
  summary: "Cross-language (C, C++ and/or Python) Timing + Memory Measurements including auto-timers and temporary memory calculation"
